const messages: Record<string, string> = {
  'auth.invalid_credentials': 'E-mail ou senha incorretos.',
  'auth.too_many_attempts': 'Muitas tentativas. Aguarde alguns minutos e tente de novo.',
  'auth.weak_password': 'A senha precisa ter entre 10 e 128 caracteres.',
  'auth.forbidden': 'Você não tem permissão para esta ação.',
  'auth.unauthenticated': 'Sua sessão expirou. Entre novamente.',
  'invite.invalid': 'Este link expirou ou já foi usado. Peça um novo.',
  'tenant.not_found': 'Empresa não encontrada.',
  'tenant.invalid_slug': 'Use só letras minúsculas, números e hífen no endereço.',
  'tenant.slug_taken': 'Esse endereço já está em uso.',
  'tenant.invalid_request': 'Preencha todos os campos.',
  'users.invalid_email': 'Informe um e-mail válido.',
  'users.email_taken': 'Esse e-mail já está em uso por outro participante.',
  'users.name_required': 'Informe o nome do participante.',
  'users.invalid_supervisor': 'Selecione um indicador válido.',
  'plan.invalid_effective_from': 'Escolha o mês de início da vigência.',
  'hinova.credenciais_invalidas': 'A Hinova não aceitou essas credenciais. Confira usuário, senha e token.',
  'hinova.nao_configurado': 'Configure as credenciais da Hinova antes de buscar voluntários.',
  'hinova.vinculo_duplicado': 'Esse usuário ou esse voluntário já está vinculado a outro registro.',
  'hinova.campos_incompletos': 'Preencha todos os dados do voluntário antes de confirmar.',
  'fechamento.competencia_not_closed': 'Só é possível confirmar competências já encerradas.',
  'fechamento.already_confirmed': 'Essa competência já foi confirmada.',
  'fechamento.requires_full_visibility': 'Você não tem permissão para confirmar o fechamento.',
  'fechamento.invalid_transition': 'Confirme a competência antes de provisionar.',
  'fechamento.not_found': 'Fechamento não encontrado para essa competência.',
  'internal.error': 'Não foi possível falar com o servidor. Tente novamente em instantes.',
  'convite.link_invalido': 'Esse link não é válido ou expirou.',
  'convite.indicador_sem_hinova': 'Você precisa estar vinculado a um código de voluntário na Hinova antes de gerar seu link.',
  'request.invalid': 'Preencha todos os campos obrigatórios.',
  'solicitacao.not_found': 'Solicitação não encontrada.',
  'solicitacao.ja_resolvida': 'Essa solicitação já foi resolvida.',
  'solicitacao.cpf_ja_cadastrado': 'Esse CPF já está cadastrado na Hinova. Resolva manualmente antes de aprovar.',
  'solicitacao.indicador_sem_hinova': 'O indicador não está mais vinculado a um código de voluntário na Hinova.',
};

export function messageFor(code: string): string {
  return messages[code] ?? 'Não foi possível concluir. Tente novamente.';
}
