const test=require('node:test'), assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
function load(saved){const mem={};if(saved)mem['aprovec-network-v1']=saved;const ctx={window:{},localStorage:{getItem:k=>mem[k]||null,setItem:(k,v)=>mem[k]=v}};vm.createContext(ctx);for(const f of ['data.js','network.js'])vm.runInContext(fs.readFileSync('mockup/'+f,'utf8'),ctx);return {n:ctx.window.aprovecNetwork,data:ctx.window.aprovecData,mem};}
test('reproduz os valores do PDF e considera somente indicação direta',()=>{const {n}=load();assert.equal(n.totals().received,35000);assert.equal(n.totals().manager,350);assert.equal(n.personTotals('joao').total,1600);assert.equal(n.personTotals('maria').total,800);assert.equal(n.personTotals('pedro').total,350);assert.equal(n.totals().payroll,3100);assert.deepEqual(Array.from(n.children('joao'),p=>p.id),['maria']);});
test('base global conta cada boleto uma vez e exclui valores não pagos',()=>{const {n}=load();assert.equal(new Set(n.rows.map(r=>r.id)).size,n.rows.length);assert.equal(n.rows.filter(r=>r.status==='recebido').length,165);assert.equal(n.totals().overdue,5400);assert.equal(n.totals().upcoming,2000);assert.equal(n.totals().cancelled,1600);});
test('impede ciclos, autorreferência e emails duplicados',()=>{const {n}=load();assert.throws(()=>n.savePerson({id:'joao',name:'João Silva',email:'joao@exemplo.com',parentId:'pedro'}),/ciclo/i);assert.throws(()=>n.savePerson({id:'maria',name:'Maria Oliveira',email:'maria@exemplo.com',parentId:'maria'}),/próprio/i);assert.throws(()=>n.savePerson({name:'Outro nome',email:n.person('joao').email,parentId:null}),/e-mail/i);});
test('cadastro persiste, começa com zero e pode mudar de indicador',()=>{const {n,mem}=load();const p=n.savePerson({name:'Ana Souza',email:'ana@exemplo.com',parentId:'joao'});assert.equal(n.personTotals(p.id).total,0);assert.equal(n.children('joao').length,2);n.savePerson({...p,parentId:'pedro'});assert.equal(n.person(p.id).parentId,'pedro');assert.equal(load(mem['aprovec-network-v1']).n.person(p.id).name,'Ana Souza');});
test('percentuais recalculam sem comissão em cascata e preservam histórico',()=>{const {n,data}=load();assert.throws(()=>n.saveRates({own:-1,referral:2,manager:1}),/percentuais/i);assert.throws(()=>n.saveRates({own:90,referral:10,manager:1}),/100/i);n.saveRates({own:8,referral:3,manager:2});assert.equal(n.personTotals('joao').total,1900);assert.equal(n.personTotals('maria').total,950);assert.equal(n.totals().manager,700);assert.equal(n.totals().payroll,3950);assert.equal(data.august.total,1440);});
test('mudar indicador redistribui somente a indicação, preservando base global',()=>{const {n}=load();n.savePerson({...n.person('pedro'),parentId:'joao'});assert.equal(n.personTotals('joao').referral,300);assert.equal(n.personTotals('maria').referral,0);assert.equal(n.totals().manager,350);});

test('cadastro corrompido volta ao exemplo e armazenamento indisponível mantém a sessão',()=>{const {n}=load('{invalid');assert.equal(n.totals().manager,350);const ctx={window:{},localStorage:{getItem:()=>{throw Error('indisponível');},setItem:()=>{throw Error('indisponível');}}};vm.createContext(ctx);for(const f of ['data.js','network.js'])vm.runInContext(fs.readFileSync('mockup/'+f,'utf8'),ctx);ctx.window.aprovecNetwork.saveRates({own:8,referral:2,manager:1});assert.equal(ctx.window.aprovecNetwork.rates.own,8);assert.equal(ctx.window.aprovecNetwork.persistent,false);});

test('cadastro e persistência aceitam mais de 200 pessoas em níveis sucessivos',()=>{const {n,mem}=load();let parent='pedro';for(let i=0;i<205;i++)parent=n.savePerson({name:'Participante '+i,email:'p'+i+'@exemplo.com',parentId:parent}).id;assert.equal(n.people.length,209);const restored=load(mem['aprovec-network-v1']).n;assert.equal(restored.people.length,209);assert.equal(restored.person(parent).name,'Participante 204');assert.equal(restored.totals().manager,350);});
